/**
 * JSON Schema export of the Rule Set contract (contract/rule-set.schema.json).
 *
 * The file is generated from the Zod schema by `npm run contract:export` and
 * committed; tests/contract/json-schema.test.ts fails if it is out of date.
 */
import { z } from 'zod';
import { RuleSetSchema } from './schema.js';
import { CONTRACT_VERSION } from './version.js';

export const JSON_SCHEMA_ID = `urn:lsc:rule-set:${CONTRACT_VERSION}`;

/** Repository-relative location of the committed schema file. */
export const JSON_SCHEMA_RELATIVE_PATH = 'contract/rule-set.schema.json';

export function buildRuleSetJsonSchema(): Record<string, unknown> {
  const generated = z.toJSONSchema(RuleSetSchema, {
    target: 'draft-2020-12',
    unrepresentable: 'throw',
    io: 'input',
  }) as Record<string, unknown>;
  const { $schema, ...rest } = generated;
  return {
    $schema,
    $id: JSON_SCHEMA_ID,
    title: `LSC Rule Set (contract ${CONTRACT_VERSION})`,
    $comment:
      'GENERATED by `npm run contract:export` from src/contract/schema.ts. Do not edit by hand. ' +
      'Cross-field rules that JSON Schema cannot express are listed in contract/CONTRACT.md §5; ' +
      'run `lsc validate-ruleset` or reimplement them.',
    ...rest,
  };
}

/** Deterministic file content: 2-space indentation, trailing newline. */
export function serializeRuleSetJsonSchema(): string {
  return `${JSON.stringify(buildRuleSetJsonSchema(), null, 2)}\n`;
}
